{
 "title": "JWT Pizza Service",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= ``"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(purchase_metrics_milliseconds{source=\"jwt-pizza-service\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(http_request_latency_milliseconds{source=\"jwt-pizza-service\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "All"
    },
    {
     "expr": "rate(http_requests_total{method=\"DELETE\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "rate(http_requests_total{method=\"GET\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "rate(http_requests_total{method=\"POST\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "rate(http_requests_total{method=\"PUT\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Authentication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(auth_attempts_total{status=\"success\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(auth_attempts_total{status=\"failure\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Usage Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percentage{source=\"jwt-pizza-service\"}",
     "legendFormat": "Cpu Usage"
    },
    {
     "expr": "memory_usage_percentage{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "active_users{source=\"jwt-pizza-service\"}",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "rate(purchase_metrics_attempts{status=\"revenue\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "rate(purchase_metrics_attempts_total{status=\"success\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza Purchases"
    },
    {
     "expr": "rate(purchase_metrics_attempts_total{status=\"failure\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Purchase Failures"
    }
   ]
  }
 ]
}